services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    restart: unless-stopped
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 1112
    restart: unless-stopped